# Generated by Django 4.1.4 on 2022-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
